USB_VID = 0x239A
USB_PID = 0x808A
USB_PRODUCT = "STM32F407VET Black Board - CPy"
USB_MANUFACTURER = "STMicroelectronics"

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = W25Q16JVxQ

MCU_SERIES = F4
MCU_VARIANT = STM32F407xx
MCU_PACKAGE = LQFP100_f4

LD_COMMON = boards/common_default.ld
LD_FILE = boards/STM32F407xe_nofs.ld

# UF2 boot option
# LD_BOOT = boards/STM32F407xe_boot.ld
# UF2_OFFSET = 0x8010000
# CFLAGS += -DCFG_TUSB_OTG_VBUS_SENSE=OPT_OTG_VBUS_SENSE_DISABLE
# CFLAGS += -DCFG_TUSB_OTG_ID=OPT_OTG_ID_DISABLE
# CFLAGS += -DCFG_TUSB_DEBUG=3
# CFLAGS += -DLOGGER=rtt
# CFLAGS += -DCFG_TUSB_DEBUG_PRINTF=trace_printf

# SRC_C += boards/stm32_f4ve/printf.c

OPTIMIZATION_FLAGS = -Og

CIRCUITPY_CANIO = 0

# Too big for the flash
CIRCUITPY_AUDIOCORE = 0
CIRCUITPY_AUDIOPWMIO = 0
CIRCUITPY_ULAB = 0
CIRCUITPY_BITMAPTOOLS = 0
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_MSGPACK = 0
CIRCUITPY_VECTORIO = 0
